"From Cute to Brute" Secret Lair deck
taw/magic-preconstructed-decks pull request #40
Opened 2023-05-15 11:48 UTC by davidmartos96

Hello, here is a work in progress on the From Cute to Brute deck.
The Commander and 4 cards are the new Secret Lair printings. I specified the set and number for those.
The remaining 95 cards are stamped in the corner with the Planeswalker icon, same as the other Secret Lair deck, "Heads I Win, Tails you Lose" (PHED) https://scryfall.com/sets/phed

Since these printings are not yet available on Scryfall or MTGJSON I used the sld folder, but that should probably be changed once we have a particular set code for the deck, so that the printings resolve correctly. 

https://magic.wizards.com/en/news/announcements/commander-returns-to-secret-lair-with-from-cute-to-brute
https://secretlair.wizards.com/us/product/819075/secret-lair-commander-deck-from-cute-to-brute
https://mtg.fandom.com/wiki/Secret_Lair_Commander_Deck:_From_Cute_to_Brute

2023-05-15 15:38 UTC, axxroytovu requested changes

2023-05-15 15:38 UTC, axxroytovu commented on data/cmd/sld/From Cute to Brute.txt
> +COMMANDER: 1 Esika, God of the Tree // The Prismatic Bridge [SLD:1155]
Numbering with double faced cards should only associate the front face. eg:
`COMMANDER: 1 Esika, God of the Tree [SLD:1155a]`

2023-05-15 15:41 UTC, axxroytovu commented
@taw this is breaking because the SLD "set" release date doesn't match up with the deck release date, and cards like Dennick, Pious Apprentice are breaking. 

`deck_printing_resolver.rb:124:in 'resolve_set': All printings of Dennick, Pious Apprentice from the future`

Can we adjust the deck parser to use the recorded deck release date if it exists? Right now it just uses `release_date(deck_set_code)`.

2023-05-15 15:54 UTC, axxroytovu commented on data/cmd/sld/From Cute to Brute.txt
> +COMMANDER: 1 Esika, God of the Tree // The Prismatic Bridge [SLD:1155]
This only applies to the numbered cards, the non-numbered double faced cards are fine.

2023-05-15 16:48 UTC, taw commented on data/cmd/sld/From Cute to Brute.txt
> +COMMANDER: 1 Esika, God of the Tree // The Prismatic Bridge [SLD:1155]
I added a step to deck indexer that can handle both [SLD:1155] and [SLD:1155a]

2023-05-15 16:48 UTC, taw commented
@axxroytovu Date handling can now deal with this.

2023-05-15 16:50 UTC, axxroytovu commented on data/cmd/sld/From Cute to Brute.txt
> +1 Sphinx of the Second Sun
This specific card can't resolve with the current search rules. Should add [CMR:99] for now.

2023-05-16 08:42 UTC, davidmartos96 commented on data/cmd/sld/From Cute to Brute.txt
> +1 Sphinx of the Second Sun
@taw Do you want to merge and index the deck anyway? Or do you prefer to wait for the correct printings?

2023-05-16 09:44 UTC, davidmartos96 commented on data/cmd/sld/From Cute to Brute.txt
> +1 Sphinx of the Second Sun
We can wait a bit. I just found out that the other 95 cards are now in Scryfall. They will be fetched by MTGJSON in the next update and we can index them here afterwards.
https://scryfall.com/sets/pctb

2023-05-17 09:37 UTC, merged